package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer age;
	private boolean error;

	private java.lang.String fatherName;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public boolean isError() {
		return this.error;
	}

	public void setError(boolean error) {
		this.error = error;
	}

	public java.lang.String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(java.lang.String fatherName) {
		this.fatherName = fatherName;
	}

	public Person(java.lang.String name, java.lang.Integer age, boolean error,
			java.lang.String fatherName) {
		this.name = name;
		this.age = age;
		this.error = error;
		this.fatherName = fatherName;
	}

}